branch-defaults:
  default:
    environment: ramsay-project-env
environment-defaults:
  ramsay-project-env:
    branch: null
    repository: null
global:
  application_name: ramsay-project
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
