# Generated by Django 2.1.7 on 2019-03-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('artifact', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ledger')),
                ('materials', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True)),
                ('origin', models.CharField(max_length=64)),
                ('collection', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=64)),
                ('license_link', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('customer_first', models.CharField(max_length=64)),
                ('customer_last', models.CharField(max_length=64)),
                ('page', models.IntegerField()),
                ('origin_description', models.TextField()),
                ('production_country', models.CharField(blank=True, max_length=64)),
                ('production_detail', models.CharField(blank=True, max_length=128)),
                ('materials_location', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField()),
                ('unit_number', models.IntegerField()),
                ('unit_suffix', models.CharField(max_length=64)),
                ('original_price', models.IntegerField(default=0.0)),
                ('modern_pounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modern_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('analytics', models.TextField()),
                ('citation', models.ManyToManyField(related_name='ledger_entries', to='ledger.Citation')),
            ],
        ),
    ]
